# Generated by Django 4.2.3 on 2023-08-07 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='version',
        ),
        migrations.RemoveField(
            model_name='version',
            name='versionRelease',
        ),
        migrations.AddField(
            model_name='version',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Live',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfRelease', models.DateField()),
                ('live', models.BooleanField(default=0)),
                ('liveFeature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theLiveFeature', to='coreApp.feature')),
                ('liveVersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theLiveVersion', to='coreApp.version')),
            ],
        ),
    ]
