# Generated by Django 4.2.3 on 2023-08-08 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0002_remove_feature_version_remove_version_versionrelease_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='dateOfRelease',
            field=models.DateField(blank=True),
        ),
    ]
