# Generated by Django 4.2.3 on 2023-08-08 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0003_alter_live_dateofrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='live',
            name='dateOfRelease',
            field=models.DateField(blank=True, null=True),
        ),
    ]
