# Generated by Django 4.2.3 on 2023-08-20 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coreApp', '0004_alter_live_dateofrelease'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=255)),
                ('releaseType', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
    ]
