# list01 = [
#     "HiveMind Wellness",
#     "MentalHive Connect",
#     "HiveTalk Therapeutics",
#     "MoodHive Chat",
#     "HiveHealth Log",
#     "HiveSymptom Tracker",
#     "HiveTherapy Hub",
#     "HiveHeart Wellness",
#     "HiveSupport Network",
#     "HiveShare Health"
# ]
# list02 = [
#     "CodeHive Wellness",
#     "DevMind Hive",
#     "MentalHive CodeChat",
#     "HiveStack Therapy",
#     "HiveDebug Health",
#     "MoodCode Hive",
#     "HiveLog Connect",
#     "HiveTech Therapeutics",
#     "HiveSymptom Tracker Pro",
#     "CodeHeal Hub"
# ]
# list03 = [
#     "MindHive Connect",
#     "CodeBee Support",
#     "Buzzing Minds Network",
#     "HiveMind Wellness",
#     "TechBees Community",
#     "BeeWell Programming",
#     "CollaboraMinds",
#     "HoneyMind Hub",
#     "UnityTech Hive",
#     "Programmer's Sanctuary"
# ]
# list04 = [
#     "DevWell Connect",
#     "CodeCrafters Network",
#     "TechMinds Collective",
#     "ProgResilience Hub",
#     "MindfulCoder Community",
#     "EmpowerTech Forum",
#     "Programmer's Haven",
#     "Resilient Coders Club",
#     "CodeCompassion Hub",
#     "Mindful Tech Tribe",
# ]
# list05 = [
#     "TechWell Connect",
#     "MindfulTech Collective",
#     "CodeCrafters Community",
#     "NetworkNurturers Hub",
#     "DataMinds Oasis",
#     "ResilientTech Tribe",
#     "TechHealer Network",
#     "MindfulSciTech Community",
#     "Compassionate Coders Club",
#     "Engineer's Resilience Hub"
# ]
# list06 = [
#     "UnityTech Hive",
#     "BeeMind Collective",
#     "CodeHive Support",
#     "MindfulBee Network",
#     "TechHive Wellness",
#     "CompassionCoders Hive",
#     "HiveMental Tech",
#     "Honeybee Resilience",
#     "BeeWell Engineers",
#     "HiveHeart TechHub"
# ]
# list07 = [
# "HiveMinds Network",
# "CodeSupport Hive",
# "BeeWell TechHub",
# "UnityEngineers Hive",
# "HiveHeart Connections",
# "MindfulTech Beehive",
# "TechNurturers Collective",
# "CodeCrafters Hive",
# "ResilienceBee Hub",
# "BeeMind Professionals",
# "Compassionate Coders Hive",
# "HiveSoul Engineers",
# "TechWell Community",
# "BeeHealer Network",
# "CodeCompassion Hive",
# "UnityTech Tribe",
# "HiveMind Wellness Hub",
# "Mindful Engineers Network",
# "BeeHive Resilience",
# "HiveSquad Tech",
# "TechCare Beehive",
# "MindfulCreators Hive",
# "Engineer's HiveHeart",
# "HiveSupport Professionals",
# "CompassionTech Network",
# "BeeConnected Engineers",
# "CodeUnity Hive",
# "HiveMental Wellness",
# "HiveCrafters Community",
# "BeeCode Resilience",
# "TechBee Wellbeing",
# "MindfulHive Professionals",
# "Engineer's Resilience Hive",
# "CodeMinds Collective",
# "HiveSoul Support",
# "TechCaring Hive",
# "BeeBuilders Network",
# "UnityCode Hub",
# "HiveCompassion Professionals",
# "MindfulTech Tribes",
# "HiveHealers Collective",
# "BeeConnected Tech",
# "CodeSquad Resilience",
# "UnityMind Engineers",
# "HiveCare Community",
# "TechResilience HiveHeart",
# "BeeWell Creators",
# "CompassionHive Network",
# "HiveUnity Professionals",
# "TechMinds Wellness"
# ]
# list08 = [
#     "BeeConnect Tech",
#     "CodeHealers Hive",
#     "MindfulHive Network",
#     "TechSupport HiveHeart",
#     "HiveMind Unity",
#     "ResilientBee Hub",
#     "CompassionTech Collective",
#     "Engineer's HiveMinds",
#     "HiveWell Professionals",
#     "UnityCode Connect",
#     "BeeCrafters Resilience",
#     "TechCompassion Tribe",
#     "HiveHeart Engineers",
#     "CodeNurturers Network",
#     "MindfulCreators HiveHub",
#     "BeeMind Wellness Community",
#     "HiveSupport Innovators",
#     "HiveSoul Techies",
#     "UnityMind Resilience",
#     "CodeCaring HiveHeart",
#     "BeeCraftsmen Network",
#     "TechUnity Professionals",
#     "MindfulBuilders Hive",
#     "Engineer's Compassion Hub",
#     "HiveMental Innovators",
#     "ResilientTech Tribe",
#     "CodeCreators Connect",
#     "HiveHeart TechCraft",
#     "BeeCompassion Wellness",
#     "HiveWell Professionals",
#     "UnitySupport Hive",
#     "TechHealers Collective",
#     "MindfulMinds Network",
#     "HiveMind Innovators",
#     "BeeCode Resilience Hub",
#     "CodeCrafting Community",
#     "TechSoul Wellness",
#     "Engineer's Compassion Network",
#     "HiveUnity Creators",
#     "ResilientHive Innovators",
#     "MindfulTech HiveCraft",
#     "BeeHealers Professionals",
#     "HiveSupport Techies",
#     "CodeMenders Collective",
#     "UnityCode Resilience",
#     "TechCrafters HiveHeart",
#     "MindfulEngineers Network",
#     "HiveCompassion Innovators",
#     "BeeUnity Professionals",
#     "HiveMind Wellness Tribe",
# ]
# list09 = [
#     "HiveSquad Connect",
#     "TechHive Hub",
#     "DataMinds Collective",
#     "CodeHive Network",
#     "Buzzing Minds Community",
#     "HiveStack Tribe",
#     "Debug Haven",
#     "DevCollective",
#     "HiveTech Oasis",
#     "CommunityCoders Hub",
#     "TechTribe Network",
#     "CodeHive Oasis",
#     "HiveSquad Oasis",
#     "DataMinds Hub",
#     "Buzzing Tech Collective",
#     "HiveStack Network",
#     "Debug Community",
#     "DevHive Tribe",
#     "TechHaven Collective",
#     "CodeTribe Hub",
#     "HiveMinds Oasis",
#     "HiveSquad Network",
#     "DataHive Connect",
#     "Debug Tribe",
#     "DevTech Community",
#     "CodeOasis Network",
#     "HiveCollective Haven",
#     "TechTribe Oasis",
#     "CommunityMinds Hub",
#     "HiveStack Connect",
#     "DataTech Oasis",
#     "Buzzing Collective Haven",
#     "DebugSquad Hub",
#     "HiveCommunity Network",
#     "DevHaven Oasis",
#     "CodeTribe Collective",
#     "HiveOasis Haven",
#     "TechStack Network",
#     "DataTribe Oasis",
#     "BuzzingHive Hub",
#     "DebugMinds Collective",
#     "HiveSquad Oasis Network",
#     "CommunityCode Haven",
#     "DevCollective Oasis",
#     "HiveTech Tribe",
#     "DataHive Oasis Network",
#     "CodeHub Community",
#     "DebugTribe Network",
#     "HiveMinds TechHaven",
#     'TechSquad Hive'
# ]
# list10 = [
#     "BuzzingHive Hub",
#     "HiveBuzzing Network",
#     "TechBuzzing Collective",
#     "DataMinds Buzz",
#     "BuzzingCode Hive",
#     "BuzzingTech Community",
#     "HiveTribe Buzz",
#     "BuzzingSquad Oasis",
#     "Debugging Buzz Hub",
#     "BuzzingMinds Collective",
#     "DevBuzzing Hive",
#     "HiveStack Buzz Network",
#     "BuzzingCommunity Tech",
#     "DataTribe Buzz Oasis",
#     "HiveBuzzing Haven",
#     "BuzzingHub Network",
#     "HiveTech Buzz Collective",
#     "BuzzingData Minds",
#     "BuzzingSquad Network",
#     "HiveCollective Buzz Oasis",
#     "TechTribe Buzzing Hub",
#     "BuzzingDebug Oasis",
#     "DevBuzzing Network",
#     "BuzzingCode Tribe",
#     "HiveOasis Buzz",
#     "BuzzingHaven Network",
#     "BuzzingMinds HiveStack",
#     "HiveBuzzing Oasis Tech",
#     "BuzzingData Collective",
#     "BuzzingCommunity Hive",
#     "DebugTribe Buzzing Hub",
#     "HiveSquad Buzz Network",
#     "TechBuzzing Oasis",
#     "HiveTech Buzzing Tribe",
#     "BuzzingCollective Data",
#     "HiveBuzzing Community Hub",
#     "BuzzingCode Hive Oasis",
#     "BuzzingData Tech",
#     "DevBuzzing Buzz Haven",
#     "HiveOasis Buzzing Network",
#     "BuzzingHive Stack",
#     "BuzzingHub DataMinds",
#     "HiveBuzzing Collective Tech",
#     "BuzzingTribe HiveStack",
#     "BuzzingTech Buzz Community",
#     "HiveSquad Buzzing Oasis",
#     "BuzzingDebug Collective",
#     "HiveCollective TechBuzz",
#     "BuzzingMinds Hive Network",
#     "BuzzingCommunity Oasis",
# ]
# list11 = [
#     "DebuggingHive Hub",
#     "HiveDebugging Network",
#     "TechDebugging Collective",
#     "DataMinds Debug",
#     "DebuggingCode Hive",
#     "DebuggingTech Community",
#     "HiveTribe Debug",
#     "DebuggingSquad Oasis",
#     "HiveStack Debugging Hub",
#     "DebuggingMinds Collective",
#     "DevDebugging Hive",
#     "HiveBuzzing Debugging Network",
#     "DebuggingCommunity Tech",
#     "DataTribe Debug Oasis",
#     "HiveDebugging Haven",
#     "DebuggingHub Network",
#     "HiveTech Debugging Collective",
#     "DebuggingData Minds",
#     "DebuggingSquad Network",
#     "HiveCollective Debug Oasis",
#     "TechTribe Debugging Hub",
#     "DebuggingBuzzing Oasis",
#     "DevDebugging Network",
#     "DebuggingCode Tribe",
#     "HiveOasis Debugging Buzz",
#     "DebuggingHaven Network",
#     "DebuggingMinds HiveStack",
#     "HiveDebugging Oasis Tech",
#     "DebuggingData Collective",
#     "DebuggingCommunity Hive",
#     "DebugTribe Debugging Hub",
#     "HiveSquad Debugging Network",
#     "TechDebugging Oasis",
#     "HiveTech Debugging Tribe",
#     "DebuggingCollective Data",
#     "HiveDebugging Community Hub",
#     "DebuggingCode Hive Oasis",
#     "DebuggingData Tech",
#     "DevDebugging Debug Haven",
#     "HiveOasis Debugging Network",
#     "DebuggingHive Stack",
#     "DebuggingHub DataMinds",
#     "HiveDebugging Collective Tech",
#     "DebuggingTribe HiveStack",
#     "DebuggingTech Debug Community",
#     "HiveSquad Debugging Oasis",
#     "DebuggingBuzzing Collective",
#     "HiveCollective TechDebug",
#     "DebuggingMinds Hive Network",
#     "DebuggingCommunity Debug Oasis",
# ]
# list12 = [
#     "MindfulTech Connect",
#     "CodeWell Collective",
#     "UnityMinds Network",
#     "TechSupport Haven",
#     "DataTribe Hub",
#     "ResilienceCrafters Community",
#     "Developer's Oasis",
#     "WellBeing Code Tribe",
#     "MindHealers Network",
#     "TechUnity Hub",
#     "CodeCrafted Minds",
#     "DataResilience Collective",
#     "MindfulStack Community",
#     "DevWell Oasis",
#     "Supportive Coders Network",
#     "UnityTech Hub",
#     "ResilienceData Tribe",
#     "MindfulCreators Network",
#     "TechSquad WellBeing",
#     "CodeCompassion Oasis",
#     "DataMindful Hub",
#     "Developer's Unity Network",
#     "WellTech Community",
#     "MindfulTribe Collective",
#     "ResilienceCrafted Oasis",
#     "CodeHealers Network",
#     "UnitySupport Hub",
#     "TechWell Collective",
#     "DataHealing Minds",
#     "MindfulCrafters Oasis",
#     "DevResilience Network",
#     "SupportiveTech Hub",
#     "CodeUnity Tribe",
#     "WellBeing Crafters Network",
#     "MindHealers Oasis",
#     "UnityMinds Collective",
#     "DataTribe WellTech",
#     "MindfulDevelopers Hub",
#     "ResilienceCode Network",
#     "TechSupportive Oasis",
#     "CraftedUnity Minds",
#     "CodeWellBeing Hub",
#     "MindfulTech Tribe",
#     "DataHealers Oasis",
#     "DevTribe Collective",
#     "UnityCrafters Network",
#     "WellTech Minds",
#     "MindfulSquad Hub",
#     "ResilienceSupportive Community",
#     "CodeMindful Oasis"
# ]
# list13 = [
#     "MindfulTech Connect",
#     "CodeWell Collective",
#     "UnityMinds Network",
#     "TechSupport Haven",
#     "DataTribe Hub",
#     "Developer's Oasis",
#     "WellBeing Code Tribe",
#     "MindHealers Network",
#     "TechUnity Hub",
#     "MindfulStack Community",
#     "DevWell Oasis",
#     "Supportive Coders Network",
#     "UnityTech Hub",
#     "MindfulCreators Network",
#     "TechSquad WellBeing",
#     "CodeCompassion Oasis",
#     "DataMindful Hub",
#     "Developer's Unity Network",
#     "WellTech Community",
#     "MindfulTribe Collective",
#     "TechWell Collective",
#     "DataMindful Hub",
#     "Developer's Unity Network",
#     "WellTech Community",
#     "MindfulTribe Collective",
#     "TechWell Collective",
#     "DataHealing Minds",
#     "MindfulCrafters Oasis",
#     "UnitySupport Hub",
#     "CodeUnity Tribe",
#     "WellBeing WellTech",
#     "MindHealers Oasis",
#     "UnityMinds Collective",
#     "DataTribe WellTech",
#     "MindfulDevelopers Hub",
#     "TechSupportive Oasis",
#     "CodeWellBeing Hub",
#     "MindfulTech Tribe",
#     "DataHealers Oasis",
#     "DevTribe Collective",
#     "UnityTech Minds",
#     "WellTech Hub",
#     "MindfulSquad Oasis",
#     "CodeMindful Network",
#     "TechSupportive Tribe",
#     "MindfulConnect Haven",
#     "DataMinds Oasis",
#     "UnitySupport Network",
#     "Developer's WellBeing Hub",
#     "WellTech Connect"
# ]
# list14 = [
#     "Developers Oasis",
#     "MindfulDevelopers Hub",
#     "WellBeing Collective",
#     "DevMinds Network",
#     "HiveSquad Oasis",
#     "MindfulOasis Hub",
#     "Developers Network",
#     "WellBeing Hive",
#     "BuzzingMinds Oasis",
#     "Collective Community",
#     "DevWellBeing Network",
#     "MindfulMinds Hub",
#     "Developers HiveSquad",
#     "Network Oasis",
#     "MindfulCollective Hub",
#     "WellBeing Network",
#     "Oasis Minds",
#     "HiveSquad Community",
#     "Developers BuzzingMinds",
#     "Collective Oasis",
#     "MindfulNetwork Hub",
#     "WellMindful Hive",
#     "DevOasis Oasis",
#     "MindfulHive Network",
#     "Developers BuzzingCommunity",
#     "HiveSquad Minds",
#     "WellBeing Oasis Network",
#     "Developers Collective",
#     "Network Minds",
#     "MindfulHiveSquad Oasis",
#     "Oasis Network",
#     "WellMinds Hub",
#     "BuzzingCollective Network",
#     "DevHiveSquad Oasis",
#     "MindfulCommunity Hive",
#     "Developers Hub Oasis",
#     "Collective Minds",
#     "HiveSquad Network",
#     "WellBeing Oasis Hive",
#     "DevBuzzingMinds Hub",
#     "Network Collective",
#     "MindfulHive Oasis",
#     "Developers Hive",
#     "WellMindful Oasis",
#     "Oasis Community",
#     "HiveSquad Minds Network",
#     "DevMinds Oasis",
#     "Collective WellBeing Hub",
#     "MindfulNetwork Oasis",
#     "Developers Community Hive",
# ]
# list15 = [
#     "Developers Thrive Hub",
#     "ThriveMind Collective",
#     "WellBeing OasisThrive",
#     "DevMinds Thrive Network",
#     "ThriveHiveSquad Oasis",
#     "MindfulThrive Oasis Hub",
#     "Developers Thrive Network",
#     "WellBeing Thrive Hive",
#     "BuzzingMinds Thrive Oasis",
#     "Collective Thrive Community",
#     "DevWellBeing Thrive Network",
#     "MindfulMinds Thrive Hub",
#     "Developers HiveSquad Thrive",
#     "Thrive Network Oasis",
#     "MindfulCollective Thrive Hub",
#     "WellBeing NetworkThrive",
#     "Oasis MindsThrive",
#     "HiveSquad Thrive Community",
#     "Developers BuzzingMinds Thrive",
#     "Collective Thrive Oasis",
#     "MindfulNetwork HubThrive",
#     "WellMindful Thrive Hive",
#     "DevOasis OasisThrive",
#     "MindfulHive NetworkThrive",
#     "Developers BuzzingCommunity Thrive",
#     "HiveSquad MindsThrive",
#     "WellBeing Oasis NetworkThrive",
#     "Developers Collective Thrive",
#     "Network MindsThrive",
#     "MindfulHiveSquad OasisThrive",
#     "Oasis NetworkThrive",
#     "WellMinds HubThrive",
#     "BuzzingCollective NetworkThrive",
#     "DevHiveSquad OasisThrive",
#     "MindfulCommunity HiveThrive",
#     "Developers Hub OasisThrive",
#     "Collective MindsThrive",
#     "HiveSquad NetworkThrive",
#     "WellBeing Oasis HiveThrive",
#     "DevBuzzingMinds HubThrive",
#     "Network CollectiveThrive",
#     "MindfulHive OasisThrive",
#     "Developers HiveThrive",
#     "WellMindful OasisThrive",
#     "Oasis CommunityThrive",
#     "HiveSquad Minds NetworkThrive",
#     "DevMinds OasisThrive",
#     "Collective WellBeing Thrive Hub",
#     "MindfulNetwork OasisThrive",
#     "Developers Community HiveThrive"
# ]

# list16 = []

newMaster = [
    "HiveMind Wellness",
    "MentalHive Connect",
    "HiveTalk Therapeutics",
    "MoodHive Chat",
    "HiveHealth Log",
    "HiveSymptom Tracker",
    "HiveTherapy Hub",
    "HiveHeart Wellness",
    "HiveSupport Network",
    "HiveShare Health",
    "CodeHive Wellness",
    "DevMind Hive",
    "MentalHive CodeChat",
    "HiveStack Therapy",
    "HiveDebug Health",
    "MoodCode Hive",
    "HiveLog Connect",
    "HiveTech Therapeutics",
    "HiveSymptom Tracker Pro",
    "CodeHeal Hub",
    "MindHive Connect",
    "CodeBee Support",
    "Buzzing Minds Network",
    "HiveMind Wellness",
    "TechBees Community",
    "BeeWell Programming",
    "CollaboraMinds",
    "HoneyMind Hub",
    "UnityTech Hive",
    "Programmer's Sanctuary",
    "DevWell Connect",
    "CodeCrafters Network",
    "TechMinds Collective",
    "ProgResilience Hub",
    "MindfulCoder Community",
    "EmpowerTech Forum",
    "Programmer's Haven",
    "Resilient Coders Club",
    "CodeCompassion Hub",
    "Mindful Tech Tribe",
    "TechWell Connect",
    "MindfulTech Collective",
    "CodeCrafters Community",
    "NetworkNurturers Hub",
    "DataMinds Oasis",
    "ResilientTech Tribe",
    "TechHealer Network",
    "MindfulSciTech Community",
    "Compassionate Coders Club",
    "Engineer's Resilience Hub",
    "UnityTech Hive",
    "BeeMind Collective",
    "CodeHive Support",
    "MindfulBee Network",
    "TechHive Wellness",
    "CompassionCoders Hive",
    "HiveMental Tech",
    "Honeybee Resilience",
    "BeeWell Engineers",
    "HiveHeart TechHub",
    "HiveMinds Network",
    "CodeSupport Hive",
    "BeeWell TechHub",
    "UnityEngineers Hive",
    "HiveHeart Connections",
    "MindfulTech Beehive",
    "TechNurturers Collective",
    "CodeCrafters Hive",
    "ResilienceBee Hub",
    "BeeMind Professionals",
    "Compassionate Coders Hive",
    "HiveSoul Engineers",
    "TechWell Community",
    "BeeHealer Network",
    "CodeCompassion Hive",
    "UnityTech Tribe",
    "HiveMind Wellness Hub",
    "Mindful Engineers Network",
    "BeeHive Resilience",
    "HiveSquad Tech",
    "TechCare Beehive",
    "MindfulCreators Hive",
    "Engineer's HiveHeart",
    "HiveSupport Professionals",
    "CompassionTech Network",
    "BeeConnected Engineers",
    "CodeUnity Hive",
    "HiveMental Wellness",
    "HiveCrafters Community",
    "BeeCode Resilience",
    "TechBee Wellbeing",
    "MindfulHive Professionals",
    "Engineer's Resilience Hive",
    "CodeMinds Collective",
    "HiveSoul Support",
    "TechCaring Hive",
    "BeeBuilders Network",
    "UnityCode Hub",
    "HiveCompassion Professionals",
    "MindfulTech Tribes",
    "HiveHealers Collective",
    "BeeConnected Tech",
    "CodeSquad Resilience",
    "UnityMind Engineers",
    "HiveCare Community",
    "TechResilience HiveHeart",
    "BeeWell Creators",
    "CompassionHive Network",
    "HiveUnity Professionals",
    "TechMinds Wellness",
    "BeeConnect Tech",
    "CodeHealers Hive",
    "MindfulHive Network",
    "TechSupport HiveHeart",
    "HiveMind Unity",
    "ResilientBee Hub",
    "CompassionTech Collective",
    "Engineer's HiveMinds",
    "HiveWell Professionals",
    "UnityCode Connect",
    "BeeCrafters Resilience",
    "TechCompassion Tribe",
    "HiveHeart Engineers",
    "CodeNurturers Network",
    "MindfulCreators HiveHub",
    "BeeMind Wellness Community",
    "HiveSupport Innovators",
    "HiveSoul Techies",
    "UnityMind Resilience",
    "CodeCaring HiveHeart",
    "BeeCraftsmen Network",
    "TechUnity Professionals",
    "MindfulBuilders Hive",
    "Engineer's Compassion Hub",
    "HiveMental Innovators",
    "ResilientTech Tribe",
    "CodeCreators Connect",
    "HiveHeart TechCraft",
    "BeeCompassion Wellness",
    "HiveWell Professionals",
    "UnitySupport Hive",
    "TechHealers Collective",
    "MindfulMinds Network",
    "HiveMind Innovators",
    "BeeCode Resilience Hub",
    "CodeCrafting Community",
    "TechSoul Wellness",
    "Engineer's Compassion Network",
    "HiveUnity Creators",
    "ResilientHive Innovators",
    "MindfulTech HiveCraft",
    "BeeHealers Professionals",
    "HiveSupport Techies",
    "CodeMenders Collective",
    "UnityCode Resilience",
    "TechCrafters HiveHeart",
    "MindfulEngineers Network",
    "HiveCompassion Innovators",
    "BeeUnity Professionals",
    "HiveMind Wellness Tribe",
    "HiveSquad Connect",
    "TechHive Hub",
    "DataMinds Collective",
    "CodeHive Network",
    "Buzzing Minds Community",
    "HiveStack Tribe",
    "Debug Haven",
    "DevCollective",
    "HiveTech Oasis",
    "CommunityCoders Hub",
    "TechTribe Network",
    "CodeHive Oasis",
    "HiveSquad Oasis",
    "DataMinds Hub",
    "Buzzing Tech Collective",
    "HiveStack Network",
    "Debug Community",
    "DevHive Tribe",
    "TechHaven Collective",
    "CodeTribe Hub",
    "HiveMinds Oasis",
    "HiveSquad Network",
    "DataHive Connect",
    "Debug Tribe",
    "DevTech Community",
    "CodeOasis Network",
    "HiveCollective Haven",
    "TechTribe Oasis",
    "CommunityMinds Hub",
    "HiveStack Connect",
    "DataTech Oasis",
    "Buzzing Collective Haven",
    "DebugSquad Hub",
    "HiveCommunity Network",
    "DevHaven Oasis",
    "CodeTribe Collective",
    "HiveOasis Haven",
    "TechStack Network",
    "DataTribe Oasis",
    "BuzzingHive Hub",
    "DebugMinds Collective",
    "HiveSquad Oasis Network",
    "CommunityCode Haven",
    "DevCollective Oasis",
    "HiveTech Tribe",
    "DataHive Oasis Network",
    "CodeHub Community",
    "DebugTribe Network",
    "HiveMinds TechHaven",
    'TechSquad Hive',
    "BuzzingHive Hub",
    "HiveBuzzing Network",
    "TechBuzzing Collective",
    "DataMinds Buzz",
    "BuzzingCode Hive",
    "BuzzingTech Community",
    "HiveTribe Buzz",
    "BuzzingSquad Oasis",
    "Debugging Buzz Hub",
    "BuzzingMinds Collective",
    "DevBuzzing Hive",
    "HiveStack Buzz Network",
    "BuzzingCommunity Tech",
    "DataTribe Buzz Oasis",
    "HiveBuzzing Haven",
    "BuzzingHub Network",
    "HiveTech Buzz Collective",
    "BuzzingData Minds",
    "BuzzingSquad Network",
    "HiveCollective Buzz Oasis",
    "TechTribe Buzzing Hub",
    "BuzzingDebug Oasis",
    "DevBuzzing Network",
    "BuzzingCode Tribe",
    "HiveOasis Buzz",
    "BuzzingHaven Network",
    "BuzzingMinds HiveStack",
    "HiveBuzzing Oasis Tech",
    "BuzzingData Collective",
    "BuzzingCommunity Hive",
    "DebugTribe Buzzing Hub",
    "HiveSquad Buzz Network",
    "TechBuzzing Oasis",
    "HiveTech Buzzing Tribe",
    "BuzzingCollective Data",
    "HiveBuzzing Community Hub",
    "BuzzingCode Hive Oasis",
    "BuzzingData Tech",
    "DevBuzzing Buzz Haven",
    "HiveOasis Buzzing Network",
    "BuzzingHive Stack",
    "BuzzingHub DataMinds",
    "HiveBuzzing Collective Tech",
    "BuzzingTribe HiveStack",
    "BuzzingTech Buzz Community",
    "HiveSquad Buzzing Oasis",
    "BuzzingDebug Collective",
    "HiveCollective TechBuzz",
    "BuzzingMinds Hive Network",
    "BuzzingCommunity Oasis",
    "DebuggingHive Hub",
    "HiveDebugging Network",
    "TechDebugging Collective",
    "DataMinds Debug",
    "DebuggingCode Hive",
    "DebuggingTech Community",
    "HiveTribe Debug",
    "DebuggingSquad Oasis",
    "HiveStack Debugging Hub",
    "DebuggingMinds Collective",
    "DevDebugging Hive",
    "HiveBuzzing Debugging Network",
    "DebuggingCommunity Tech",
    "DataTribe Debug Oasis",
    "HiveDebugging Haven",
    "DebuggingHub Network",
    "HiveTech Debugging Collective",
    "DebuggingData Minds",
    "DebuggingSquad Network",
    "HiveCollective Debug Oasis",
    "TechTribe Debugging Hub",
    "DebuggingBuzzing Oasis",
    "DevDebugging Network",
    "DebuggingCode Tribe",
    "HiveOasis Debugging Buzz",
    "DebuggingHaven Network",
    "DebuggingMinds HiveStack",
    "HiveDebugging Oasis Tech",
    "DebuggingData Collective",
    "DebuggingCommunity Hive",
    "DebugTribe Debugging Hub",
    "HiveSquad Debugging Network",
    "TechDebugging Oasis",
    "HiveTech Debugging Tribe",
    "DebuggingCollective Data",
    "HiveDebugging Community Hub",
    "DebuggingCode Hive Oasis",
    "DebuggingData Tech",
    "DevDebugging Debug Haven",
    "HiveOasis Debugging Network",
    "DebuggingHive Stack",
    "DebuggingHub DataMinds",
    "HiveDebugging Collective Tech",
    "DebuggingTribe HiveStack",
    "DebuggingTech Debug Community",
    "HiveSquad Debugging Oasis",
    "DebuggingBuzzing Collective",
    "HiveCollective TechDebug",
    "DebuggingMinds Hive Network",
    "DebuggingCommunity Debug Oasis",
    "MindfulTech Connect",
    "CodeWell Collective",
    "UnityMinds Network",
    "TechSupport Haven",
    "DataTribe Hub",
    "ResilienceCrafters Community",
    "Developer's Oasis",
    "WellBeing Code Tribe",
    "MindHealers Network",
    "TechUnity Hub",
    "CodeCrafted Minds",
    "DataResilience Collective",
    "MindfulStack Community",
    "DevWell Oasis",
    "Supportive Coders Network",
    "UnityTech Hub",
    "ResilienceData Tribe",
    "MindfulCreators Network",
    "TechSquad WellBeing",
    "CodeCompassion Oasis",
    "DataMindful Hub",
    "Developer's Unity Network",
    "WellTech Community",
    "MindfulTribe Collective",
    "ResilienceCrafted Oasis",
    "CodeHealers Network",
    "UnitySupport Hub",
    "TechWell Collective",
    "DataHealing Minds",
    "MindfulCrafters Oasis",
    "DevResilience Network",
    "SupportiveTech Hub",
    "CodeUnity Tribe",
    "WellBeing Crafters Network",
    "MindHealers Oasis",
    "UnityMinds Collective",
    "DataTribe WellTech",
    "MindfulDevelopers Hub",
    "ResilienceCode Network",
    "TechSupportive Oasis",
    "CraftedUnity Minds",
    "CodeWellBeing Hub",
    "MindfulTech Tribe",
    "DataHealers Oasis",
    "DevTribe Collective",
    "UnityCrafters Network",
    "WellTech Minds",
    "MindfulSquad Hub",
    "ResilienceSupportive Community",
    "CodeMindful Oasis",
    "MindfulTech Connect",
    "CodeWell Collective",
    "UnityMinds Network",
    "TechSupport Haven",
    "DataTribe Hub",
    "Developer's Oasis",
    "WellBeing Code Tribe",
    "MindHealers Network",
    "TechUnity Hub",
    "MindfulStack Community",
    "DevWell Oasis",
    "Supportive Coders Network",
    "UnityTech Hub",
    "MindfulCreators Network",
    "TechSquad WellBeing",
    "CodeCompassion Oasis",
    "DataMindful Hub",
    "Developer's Unity Network",
    "WellTech Community",
    "MindfulTribe Collective",
    "TechWell Collective",
    "DataMindful Hub",
    "Developer's Unity Network",
    "WellTech Community",
    "MindfulTribe Collective",
    "TechWell Collective",
    "DataHealing Minds",
    "MindfulCrafters Oasis",
    "UnitySupport Hub",
    "CodeUnity Tribe",
    "WellBeing WellTech",
    "MindHealers Oasis",
    "UnityMinds Collective",
    "DataTribe WellTech",
    "MindfulDevelopers Hub",
    "TechSupportive Oasis",
    "CodeWellBeing Hub",
    "MindfulTech Tribe",
    "DataHealers Oasis",
    "DevTribe Collective",
    "UnityTech Minds",
    "WellTech Hub",
    "MindfulSquad Oasis",
    "CodeMindful Network",
    "TechSupportive Tribe",
    "MindfulConnect Haven",
    "DataMinds Oasis",
    "UnitySupport Network",
    "Developer's WellBeing Hub",
    "WellTech Connect",
    "Developers Oasis",
    "MindfulDevelopers Hub",
    "WellBeing Collective",
    "DevMinds Network",
    "HiveSquad Oasis",
    "MindfulOasis Hub",
    "Developers Network",
    "WellBeing Hive",
    "BuzzingMinds Oasis",
    "Collective Community",
    "DevWellBeing Network",
    "MindfulMinds Hub",
    "Developers HiveSquad",
    "Network Oasis",
    "MindfulCollective Hub",
    "WellBeing Network",
    "Oasis Minds",
    "HiveSquad Community",
    "Developers BuzzingMinds",
    "Collective Oasis",
    "MindfulNetwork Hub",
    "WellMindful Hive",
    "DevOasis Oasis",
    "MindfulHive Network",
    "Developers BuzzingCommunity",
    "HiveSquad Minds",
    "WellBeing Oasis Network",
    "Developers Collective",
    "Network Minds",
    "MindfulHiveSquad Oasis",
    "Oasis Network",
    "WellMinds Hub",
    "BuzzingCollective Network",
    "DevHiveSquad Oasis",
    "MindfulCommunity Hive",
    "Developers Hub Oasis",
    "Collective Minds",
    "HiveSquad Network",
    "WellBeing Oasis Hive",
    "DevBuzzingMinds Hub",
    "Network Collective",
    "MindfulHive Oasis",
    "Developers Hive",
    "WellMindful Oasis",
    "Oasis Community",
    "HiveSquad Minds Network",
    "DevMinds Oasis",
    "Collective WellBeing Hub",
    "MindfulNetwork Oasis",
    "Developers Community Hive",
    "Developers Thrive Hub",
    "ThriveMind Collective",
    "WellBeing OasisThrive",
    "DevMinds Thrive Network",
    "ThriveHiveSquad Oasis",
    "MindfulThrive Oasis Hub",
    "Developers Thrive Network",
    "WellBeing Thrive Hive",
    "BuzzingMinds Thrive Oasis",
    "Collective Thrive Community",
    "DevWellBeing Thrive Network",
    "MindfulMinds Thrive Hub",
    "Developers HiveSquad Thrive",
    "Thrive Network Oasis",
    "MindfulCollective Thrive Hub",
    "WellBeing NetworkThrive",
    "Oasis MindsThrive",
    "HiveSquad Thrive Community",
    "Developers BuzzingMinds Thrive",
    "Collective Thrive Oasis",
    "MindfulNetwork HubThrive",
    "WellMindful Thrive Hive",
    "DevOasis OasisThrive",
    "MindfulHive NetworkThrive",
    "Developers BuzzingCommunity Thrive",
    "HiveSquad MindsThrive",
    "WellBeing Oasis NetworkThrive",
    "Developers Collective Thrive",
    "Network MindsThrive",
    "MindfulHiveSquad OasisThrive",
    "Oasis NetworkThrive",
    "WellMinds HubThrive",
    "BuzzingCollective NetworkThrive",
    "DevHiveSquad OasisThrive",
    "MindfulCommunity HiveThrive",
    "Developers Hub OasisThrive",
    "Collective MindsThrive",
    "HiveSquad NetworkThrive",
    "WellBeing Oasis HiveThrive",
    "DevBuzzingMinds HubThrive",
    "Network CollectiveThrive",
    "MindfulHive OasisThrive",
    "Developers HiveThrive",
    "WellMindful OasisThrive",
    "Oasis CommunityThrive",
    "HiveSquad Minds NetworkThrive",
    "DevMinds OasisThrive",
    "Collective WellBeing Thrive Hub",
    "MindfulNetwork OasisThrive",
    "Developers Community HiveThrive",
]

# def listLength(a):
#     print(len(a))
#     return

# def comboList(a):
#     list16.append(a)
#     return

# listLength(list01)
# listLength(list02)
# listLength(list03)
# listLength(list04)
# listLength(list05)
# listLength(list06)
# listLength(list07)
# listLength(list08)
# listLength(list09)
# listLength(list10)
# listLength(list11)
# listLength(list12)
# listLength(list13)
# listLength(list14)
# listLength(list15)

# comboList(list01)
# comboList(list02)
# comboList(list03)
# comboList(list04)
# comboList(list05)
# comboList(list06)
# comboList(list07)
# comboList(list08)
# comboList(list09)
# comboList(list10)
# comboList(list11)
# comboList(list12)
# comboList(list13)
# comboList(list14)
# comboList(list15)

# listLength(list16)

# masterList = [item for array in list16 for item in array]
# listLength(masterList)
# masterList.sort()
# masterList = list(set(masterList))
# print("***** Master List *****", masterList)
newMaster.sort()
masterList = list(set(newMaster))
charLists = {}

for item in masterList:
    firstChar = item[0]
    if firstChar not in charLists:
        charLists[firstChar] = []
    charLists[firstChar].append(item)

for letter in charLists:
    charLists[letter].sort()

# listLength(charLists)
# print("***** CharLists *****",charLists)
# for item in charLists:
    # print(item, "***** Each List *****",charLists[item])

sortedCharLists = {letter: charLists[letter] for letter in sorted(charLists)}

newList = []
badList = []
temp = []
for item in sortedCharLists:
    # print(item, "***** Each List *****",sortedCharLists[item])
    # print(sortedCharLists[item])
    if item == "B":
        temp = sortedCharLists[item]
        newList.append({"B":temp})
        temp = []
    if item == "C":
        temp = sortedCharLists[item]
        newList.append({"C":temp})
        temp = []
    if item == "D":
        temp = sortedCharLists[item]
        newList.append({"D":temp})
        temp = []
    if item == "E":
        temp = sortedCharLists[item]
        badList.append({"E":temp})
        temp = []
    if item == "H":
        temp = sortedCharLists[item]
        newList.append({"H":temp})
        temp = []
    if item == "M":
        temp = sortedCharLists[item]
        newList.append({"M":temp})
        temp = []
    if item == "N":
        temp = sortedCharLists[item]
        badList.append({"N":temp})
        temp = []
    if item == "O":
        temp = sortedCharLists[item]
        badList.append({"O":temp})
        temp = []
    if item == "P":
        temp = sortedCharLists[item]
        badList.append({"P":temp})
        temp = []
    if item == "R":
        temp = sortedCharLists[item]
        badList.append({"R":temp})
        temp = []
    if item == "S":
        temp = sortedCharLists[item]
        newList.append({"S":temp})
        temp = []
    if item == "T":
        temp = sortedCharLists[item]
        newList.append({"T":temp})
        temp = []
    if item == "U":
        temp = sortedCharLists[item]
        badList.append({"U":temp})
        temp = []
    if item == "W":
        temp = sortedCharLists[item]
        newList.append({"W":temp})
        temp = []
for item in newList:
    # print(item)
    for i in item:
        # print(item[i])
        if i == "W":
            for name in item[i]:
                # print(name)
                pass

keyWords = ["Network", "Hub", "Wellness", "Collective", "BeeWell", "TechHub", "BuzzingMinds", "DevHiveSquad", "HiveCollective", "HiveCommunity", "Innovators", "Community", "HiveMinds", "TechHaven", "HiveSquad", "MentalHive", "CodeChat", "MindfulBee", "MindfulCollective", "MindfulSquad", "Supportive", "TechSquad", "MindfulNetwork"]
newKeyWords = [
    "Bee", "Tech", "Mental", "Hive", "Network", "Community", "Squad", "Mindful", "Community", "Buzzing"
]
updatedKeyWords = [
    "Bee", "Tech", "Hive", "Network", "Squad", "Mindful", "Buzzing", "Buzz"
]
print(keyWords)

appList01 = [
    "NetworkWellness Hub",
    "BeeWell Collective",
    "TechHub Innovators",
    "HiveMinds Community",
    "BuzzingMinds Hive",
    "DevHiveSquad Wellness",
    "MentalHive Innovators",
    "CodeChat Hub",
    "MindfulBee Collective",
    "HiveCommunity Supportive",
    "TechSquad MindfulNetwork",
    "HiveCollective Wellness",
    "MindfulSquad Hub",
    "HiveSquad Community",
    "TechHaven Hive",
    "HiveMinds Innovators",
    "Supportive HiveNetwork",
    "BeeWell MentalHive",
    "MindfulCollective Hub",
    "MindfulNetwork Wellness",
    "HiveCommunity TechHub",
    "MentalHive Supportive",
    "BuzzingMinds CodeChat",
    "DevHiveSquad HiveSquad",
    "HiveCollective MindfulBee",
]