# Generated by Django 4.1.7 on 2023-07-06 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theAuthor', to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='MedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('freq', models.CharField(default='daily', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SymptomList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theUser', to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sugar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('level', models.IntegerField()),
                ('testSite', models.CharField(default='Finger Stick', max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('entry', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theEntry', to='logApp.day')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theOwner', to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('feeling', models.IntegerField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('feeler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theFeeler', to='userApp.user')),
                ('log', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theLog', to='logApp.day')),
                ('symptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSymptom', to='logApp.symptomlist')),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField()),
                ('dose', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theBlog', to='logApp.day')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theMed', to='logApp.medlist')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theMember', to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('journal', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='theJournal', to='logApp.day')),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWriter', to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=255)),
                ('calories', models.CharField(default=0, max_length=255)),
                ('date', models.DateTimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thePerson', to='userApp.user')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theRecord', to='logApp.day')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='week',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWeek', to='logApp.week'),
        ),
    ]
