# Generated by Django 4.1.7 on 2023-07-07 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('logApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sleep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('sleep', models.TimeField()),
                ('wake', models.TimeField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('night', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theNight', to='logApp.day')),
                ('sleeper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSleeper', to='userApp.user')),
            ],
        ),
    ]
