# Generated by Django 4.1.7 on 2023-07-02 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sugar',
            name='testSite',
            field=models.CharField(default='Finger Stick', max_length=255),
        ),
    ]
