# Generated by Django 4.0.3 on 2023-07-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('logApp', '0002_sleep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='date',
        ),
        migrations.AddField(
            model_name='food',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='food',
            name='meal',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='Water',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('water', models.IntegerField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('drinker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theDrinker', to='userApp.user')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theNote', to='logApp.day')),
            ],
        ),
    ]
