# Generated by Django 4.1.7 on 2023-07-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0003_remove_food_date_food_comments_food_meal_water'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
