# Generated by Django 4.1.7 on 2023-07-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0004_mood_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='water',
            name='comments',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='water',
            name='water',
            field=models.IntegerField(default=0),
        ),
    ]
