# Generated by Django 4.2.3 on 2023-07-30 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_profile_fitness_profile_work'),
        ('logApp', '0005_water_comments_alter_water_water'),
    ]

    operations = [
        migrations.CreateModel(
            name='FitnessList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('comments', models.TextField(blank=True)),
                ('job', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('workDay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWorkDay', to='logApp.day')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWorker', to='userApp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.TimeField()),
                ('comments', models.TextField(blank=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theExercise', to='logApp.fitnesslist')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theHuman', to='userApp.user')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theWorkout', to='logApp.day')),
            ],
        ),
    ]
