# Generated by Django 4.2.3 on 2023-07-31 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_profile_weather'),
        ('logApp', '0006_fitnesslist_work_fitness'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.CharField(max_length=255)),
                ('pressure', models.CharField(max_length=255)),
                ('humidity', models.CharField(max_length=255)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('conditions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theConditions', to='logApp.day')),
                ('userWeather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theUserWeather', to='userApp.user')),
            ],
        ),
    ]
