# Generated by Django 4.2.3 on 2023-08-17 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0009_weight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food',
        ),
        migrations.AddField(
            model_name='food',
            name='foodItem',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='theFoodItem', to='logApp.foodlist'),
            preserve_default=False,
        ),
    ]
