# Generated by Django 4.2.3 on 2023-08-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0011_food_totalcals'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlist',
            name='category',
            field=models.CharField(default='Meat', max_length=255),
        ),
    ]
