# Generated by Django 4.2.3 on 2023-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0012_foodlist_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodCat',
            field=models.CharField(default='Meat', max_length=255),
        ),
    ]
