# Generated by Django 4.2.3 on 2023-08-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0013_food_foodcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='foodCat',
            field=models.CharField(default='Meats', max_length=255),
        ),
    ]
