# Generated by Django 4.2.4 on 2023-08-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0014_alter_food_foodcat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugar',
            name='time',
            field=models.TimeField(),
        ),
    ]
