# Generated by Django 4.2.3 on 2023-09-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0015_alter_sugar_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fitness',
            name='unit',
            field=models.CharField(default='min', max_length=255),
        ),
        migrations.AddField(
            model_name='work',
            name='unit',
            field=models.CharField(default='hr', max_length=255),
        ),
        migrations.AlterField(
            model_name='fitness',
            name='duration',
            field=models.CharField(default='30', max_length=255),
        ),
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.CharField(default='4', max_length=255),
        ),
    ]
