# Generated by Django 4.2.3 on 2023-09-14 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0016_fitness_unit_work_unit_alter_fitness_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='unit',
        ),
    ]
