# Generated by Django 4.2.3 on 2023-09-15 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logApp', '0018_remove_fitness_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fitness',
            name='exercise',
        ),
        migrations.AddField(
            model_name='fitness',
            name='name',
            field=models.CharField(default='Walking', max_length=255),
            preserve_default=False,
        ),
    ]
