# Generated by Django 4.2.3 on 2023-12-28 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_passcode'),
        ('logApp', '0019_remove_fitness_exercise_fitness_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('steps', models.IntegerField()),
                ('floors', models.IntegerField()),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('stepper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theStepper', to='userApp.user')),
                ('stepping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theSteps', to='logApp.day')),
            ],
        ),
    ]
