# Generated by Django 4.2.3 on 2023-09-23 01:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0006_profile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('adminUser', models.CharField(max_length=255)),
                ('chatID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChatMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theChat', to='chatApp.chat')),
                ('chatUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theChatUser', to='userApp.user')),
            ],
        ),
    ]
