# Generated by Django 4.2.3 on 2023-07-30 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fitness',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='work',
            field=models.BooleanField(default=0),
        ),
    ]
