# Generated by Django 4.1.7 on 2023-07-05 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_user_role_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='journal',
            field=models.BooleanField(default=0),
        ),
    ]
