# Generated by Django 4.2.3 on 2023-07-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_profile_fitness_profile_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='lat',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='lon',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='zipCode',
            field=models.IntegerField(default=0),
        ),
    ]
