# Generated by Django 4.1.7 on 2023-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_profile_journal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='sleepApp',
            new_name='meds',
        ),
        migrations.AddField(
            model_name='profile',
            name='mood',
            field=models.BooleanField(default=1),
        ),
    ]
