# Generated by Django 4.2.3 on 2023-07-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_profile_lat_profile_lon_profile_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weather',
            field=models.BooleanField(default=0),
        ),
    ]
