# Generated by Django 4.2.3 on 2023-08-17 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0005_alter_profile_lat_alter_profile_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.BooleanField(default=1),
        ),
    ]
