# Generated by Django 4.2.3 on 2023-09-30 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0006_profile_weight'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('used', models.IntegerField(default=0)),
                ('usedOn', models.DateTimeField(auto_now=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theRequester', to='userApp.user')),
            ],
        ),
    ]
