# Generated by Django 4.2.3 on 2023-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0007_passcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='steps',
            field=models.BooleanField(default=0),
        ),
    ]
